stages:
  - build
  - deploy

include:
  - project: chirpwireless/ci
    file: general.yaml
  - project: chirpwireless/ci
    file: build-image.yaml
  - project: chirpwireless/ci
    file: helm.yaml
  - project: chirpwireless/ci
    file: deploy-gke-staging.yaml
  - project: chirpwireless/ci
    file: deploy-gke-prod.yaml

variables:
  IMAGE_NAME: registry.gitlab.com/chirpwireless/docs-iot
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  HELM_CHART_PATH: ./charts/docs-iot
  HELM_RELEASE_NAME: docs-iot



build:
  extends: 
    - .default
    - .build-image
  when: manual
  stage: build


deploy:staging:
  stage: deploy
  environment:
    name: staging
  variables:
    NAMESPACE: staging
    url: https://docs-iot.staging.chirpwireless.io
    VALUES_FILE: ./charts/values/staging.yaml
  extends:
    - .deploy-gke-staging
  needs:
    - build

deploy:prod:
  stage: deploy
  environment:
    name: prod
    url: https://docs.chirpwireless.io
  variables:
    EKS_CLUSTER_NAME: prod
    NAMESPACE: docs
    VALUES_FILE: ./charts/values/prod.yaml
  extends:
    - .deploy-gke-prod
  needs:
    - build
